# Generated by Django 4.2.11 on 2026-05-26 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('SAP_FUEL', 'SAP Fuel/Procurement'), ('UTILITY_ELECTRICITY', 'Utility Electricity'), ('TRAVEL', 'Corporate Travel')], db_index=True, max_length=50)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('last_import_at', models.DateTimeField(blank=True, null=True)),
                ('import_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('manual', 'Manual')], default='manual', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_payload', models.JSONField(help_text='Original JSON payload from the source system')),
                ('raw_payload_hash', models.CharField(db_index=True, editable=False, max_length=64)),
                ('external_id', models.CharField(db_index=True, help_text='Source system record ID', max_length=500)),
                ('external_timestamp', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('imported', 'Imported'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('superseded', 'Superseded')], db_index=True, default='received', max_length=20)),
                ('import_timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('import_batch_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('import_errors', models.JSONField(blank=True, default=list)),
                ('processing_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=255)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_records', to='core.datasource')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='core.organization')),
            ],
            options={
                'ordering': ['-import_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('analyst', 'Analyst'), ('viewer', 'Viewer')], default='viewer', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['active', 'created_at'], name='core_organi_active_587b12_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['name'], name='core_organi_name_d0cc3b_idx'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='core.organization'),
        ),
        migrations.AddIndex(
            model_name='rawrecord',
            index=models.Index(fields=['organization', 'status'], name='core_rawrec_organiz_114649_idx'),
        ),
        migrations.AddIndex(
            model_name='rawrecord',
            index=models.Index(fields=['organization', 'data_source', 'status'], name='core_rawrec_organiz_ed4272_idx'),
        ),
        migrations.AddIndex(
            model_name='rawrecord',
            index=models.Index(fields=['external_id'], name='core_rawrec_externa_e29608_idx'),
        ),
        migrations.AddIndex(
            model_name='rawrecord',
            index=models.Index(fields=['import_batch_id'], name='core_rawrec_import__eea544_idx'),
        ),
        migrations.AddIndex(
            model_name='rawrecord',
            index=models.Index(fields=['raw_payload_hash'], name='core_rawrec_raw_pay_0d87cf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rawrecord',
            unique_together={('organization', 'data_source', 'external_id')},
        ),
        migrations.AlterUniqueTogether(
            name='organizationuser',
            unique_together={('user', 'organization')},
        ),
        migrations.AddIndex(
            model_name='datasource',
            index=models.Index(fields=['organization', 'source_type'], name='core_dataso_organiz_c069aa_idx'),
        ),
        migrations.AddIndex(
            model_name='datasource',
            index=models.Index(fields=['organization', 'is_active'], name='core_dataso_organiz_57bd07_idx'),
        ),
        migrations.AddIndex(
            model_name='datasource',
            index=models.Index(fields=['organization', 'external_id'], name='core_dataso_organiz_c63fbf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='datasource',
            unique_together={('organization', 'name')},
        ),
    ]
