# Generated by Django 4.2.11 on 2026-05-26 14:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('locked', 'Locked')], default='pending', max_length=20)),
                ('reviewer', models.CharField(blank=True, max_length=255, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_comment', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('lock_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, null=True)),
                ('record_type', models.CharField(choices=[('NormalizedRecord', 'NormalizedRecord'), ('ApprovalRecord', 'ApprovalRecord')], max_length=100)),
                ('record_id', models.UUIDField()),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('locked', 'Locked'), ('comment_added', 'Comment Added')], max_length=20)),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('user', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['organization_id', 'timestamp'], name='approval_au_organiz_4a4dbb_idx'), models.Index(fields=['record_type', 'record_id'], name='approval_au_record__b207ff_idx')],
            },
        ),
    ]
