# Generated by Django 4.2.11 on 2026-05-26 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('normalization', '0001_initial'),
        ('approval', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrecord',
            name='normalized_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='normalization.normalizedrecord'),
        ),
    ]
