# Generated by Django 4.2.11 on 2026-05-26 14:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('SAP_FUEL', 'SAP Fuel/Procurement'), ('UTILITY_ELECTRICITY', 'Utility Electricity'), ('TRAVEL', 'Corporate Travel')], max_length=50)),
                ('file_name', models.CharField(max_length=255)),
                ('file_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.CharField(max_length=255)),
                ('row_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_data', to='core.organization')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='RawDataRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.IntegerField()),
                ('raw_content', models.JSONField()),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('is_flagged', models.BooleanField(default=False)),
                ('flag_reason', models.TextField(blank=True)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('normalized', 'Normalized'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='ingestion.rawdata')),
            ],
            options={
                'ordering': ['row_number'],
                'unique_together': {('raw_data', 'row_number')},
            },
        ),
    ]
