# Generated by Django 4.2.11 on 2026-05-26 14:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalizedRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('SAP_FUEL', 'SAP Fuel/Procurement'), ('UTILITY_ELECTRICITY', 'Utility Electricity'), ('TRAVEL', 'Corporate Travel')], max_length=50)),
                ('emission_quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('emission_unit', models.CharField(choices=[('kg_CO2e', 'Kilograms CO2e'), ('metric_tons_CO2e', 'Metric Tons CO2e')], default='kg_CO2e', max_length=50)),
                ('metric_type', models.CharField(choices=[('scope_1', 'Scope 1: Direct Emissions'), ('scope_2', 'Scope 2: Indirect - Energy'), ('scope_3', 'Scope 3: Indirect - Other')], max_length=20)),
                ('facility_id', models.CharField(blank=True, max_length=255)),
                ('time_period', models.DateField()),
                ('normalized_at', models.DateTimeField(auto_now_add=True)),
                ('normalized_by', models.CharField(max_length=255)),
                ('unit_converted_from', models.CharField(blank=True, max_length=100)),
                ('conversion_factor', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('confidence_score', models.IntegerField(default=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_records', to='core.organization')),
                ('raw_data_row', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='normalized_record', to='ingestion.rawdatarow')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=50)),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('user', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('normalized_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='normalization.normalizedrecord')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ValidationFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_code', models.CharField(help_text='Short code for the rule, e.g. NEGATIVE_QUANTITY', max_length=100)),
                ('reason', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('created_by', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(db_index=True, default=False)),
                ('resolved_by', models.CharField(blank=True, max_length=255)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('normalized_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_flags', to='normalization.normalizedrecord')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['normalized_record', 'rule_code'], name='normalizati_normali_d8c4b2_idx'), models.Index(fields=['resolved', 'created_at'], name='normalizati_resolve_0b8b70_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReviewComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reviewer_name', models.CharField(max_length=255)),
                ('reviewer_email', models.EmailField(max_length=254)),
                ('comment_text', models.TextField()),
                ('decision', models.CharField(choices=[('comment', 'Just a comment'), ('pending', 'Needs decision'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='comment', max_length=20)),
                ('requires_revision', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emission_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_comments', to='normalization.normalizedrecord')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_comments', to='core.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['emission_record', 'created_at'], name='normalizati_emissio_75be86_idx'), models.Index(fields=['organization', 'decision'], name='normalizati_organiz_170c61_idx')],
            },
        ),
    ]
